platform :ios, '9.0'
use_frameworks!

target 'TextViewDemo' do

   pod 'SnapKit'


  target 'TextViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextViewDemoUITests' do
    # Pods for testing
  end

end
